### ISSUE TITLE
Add a command to initialise the contur.yml

### ISSUE THREAD

**Issue by snufkin** [Cheppers/contur#13]
It would be very useful if a command like `contur init` could initialise the .contur.yml file in the working directory. It would ask for the entries one would usually define:
- php version
- mysql version
- before command

It should offer reasonable defaults (php version, before command should default to composer install).

The main goal is to provide a reasonable default .contur.yml file which is suitable for most of the projects.

**Comment by ghaabor** [comment]
Done in #16
